# NUMPY FUNDAMENTAL :-

#### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

#### Numpy Arrays Vs Python Sequences

    NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

    The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

    NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

    A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.


# CREATING NUMPY ARRAY  & its function

In [2]:
# np.array     # 1D array
import numpy as np
a = np.array([1,4,6,7])   # array stores same types of data  
print(a)
print(type(a))

[1 4 6 7]
<class 'numpy.ndarray'>


In [3]:
# 2D array
b = np.array([[1,5,4],[4,3,67]])
print(b)

[[ 1  5  4]
 [ 4  3 67]]


In [3]:
# 3D ARRAY
z =np.array([[[1,4,2],[1,6,8]],[[1,5,7],[1,9,0]]])
print(z)

[[[1 4 2]
  [1 6 8]]

 [[1 5 7]
  [1 9 0]]]


In [4]:
# data type array
np.array([1,2,3],dtype = float)
np.array([1,2,3],dtype = bool)
np.array([1,2,3],dtype = complex)  # run individually

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
#np.arange
a = np.arange(1,11)
b = np.arange(1,11,2)
print(a)
print(b)  # print after 2 no

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [6]:
# with arange, reshape
a = np.arange(16).reshape(2,2,2,2)  # 4D array
print(a)
# diff form
print("otrher example")

b = np.arange(1,11).reshape(2,5)
print(b)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
otrher example
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# np.ones
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
#np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
# np.random
np.random.random((3,4))  # it generate random no in b/w 0 to 1

array([[0.40826961, 0.54880065, 0.0679261 , 0.27239672],
       [0.99449428, 0.56752175, 0.50601659, 0.39034886],
       [0.8209988 , 0.52306391, 0.5332125 , 0.24739808]])

In [5]:
# np.linspace
x =np.linspace(-10,10,10)
y =np.linspace(-10,10,10,dtype =int)
print(x,y)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ] [-10  -8  -6  -4  -2   1   3   5   7  10]


In [11]:
# np.identity  # only diagonals element is one
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#  NUMPY Attributes

In [1]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print("next")
print(a2)
print("next")
print(a3)

[0 1 2 3 4 5 6 7 8 9]
next
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
next
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
# ndim  :-   its inform about given dimensions  
a3.ndim    # it gives output 3 ,  (a2.ndim gives 2)

3

In [14]:
# shape   :- it shows rows and columns (any directional) matrix
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# size :- it shows the size of any array(total no of item)
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
# itemsize
a3.itemsize

8

In [17]:
#dtype    #  shows data type of an array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# CHANGING DATA TYPE

In [18]:
# astype     # reduce the memory space cover by big data
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array operations

In [4]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print("************")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
### SCALAR OPERATIONS
# ARITHMETIC
a1**2    # power

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
#Relational
a2/2  #division

array([[ 6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5]])

In [22]:
# relational
a1 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [23]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
a1 +a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [25]:
# VECTOR OPERATIONS     # operation with array
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Function

In [26]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)    # range at 1 to 100
a1

array([[93., 25., 37.],
       [88., 95., 44.],
       [86., 12., 81.]])

In [27]:
# max/ min/sum/prod 

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))


95.0
12.0
561.0
2645138102112000.0


In [28]:
# max/ min/sum/prod 
# 0 -> col  and 1 -> row
np.max(a1,axis=0)   # output gives maxima of each column

array([93., 95., 81.])

In [29]:
# mean/median/std/var
print(np.mean(a1,axis = 1))
print(np.median(a1,axis = 0))
print(np.std(a1,axis = 1))
print(np.var(a1,axis = 0))

[51.66666667 75.66666667 59.66666667]
[88. 25. 44.]
[29.63481436 22.57333727 33.7671767 ]
[   8.66666667 1328.66666667  372.66666667]


In [30]:
#Trigonometric fumction
np.sin(a1)

array([[-0.94828214, -0.13235175, -0.64353813],
       [ 0.0353983 ,  0.68326171,  0.01770193],
       [-0.92345845, -0.53657292, -0.62988799]])

##### DOT product


In [31]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [32]:
# log and exponents
print(np.log(a1))
print("********************************")
print(np.exp(a1))

[[4.53259949 3.21887582 3.61091791]
 [4.47733681 4.55387689 3.78418963]
 [4.4543473  2.48490665 4.39444915]]
********************************
[[2.45124554e+40 7.20048993e+10 1.17191424e+16]
 [1.65163625e+38 1.81123908e+41 1.28516001e+19]
 [2.23524660e+37 1.62754791e+05 1.50609731e+35]]


In [33]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)    # range at 1 to 100
a1

array([[97., 35., 19.],
       [62., 76., 68.],
       [14.,  6., 42.]])

In [34]:
# round / floor / ceil
print(np.round(np.random.random((2,3))*100))  # .round convert into nearest intiger
print(np.floor(np.random.random((2,3))*100))  # .floor gives 6.9  to 6  ..go for last intigerrt
print(np.ceil(np.random.random((2,3))*100))   # .ceil go for forward intiger 6.9  to 9.

[[17. 99. 22.]
 [17.  4. 66.]]
[[77. 26. 77.]
 [97.  5. 80.]]
[[80.  9.  9.]
 [75. 77.  8.]]


# Indexing 

In [17]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [36]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
print(a1[0])   #  first element of array
print(a1[-1])   # last ele of array

0
9


In [3]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
print(a2[1,2])   # 6 ois in 1 st row and 2nd column
print(a2[1,0])   # 4 is 1in 1st row and 0th column

6
4


In [39]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
print(a3[1,1,1])  # 1 - 1st row of array ,, 1 - -1 st row in (1st row of array)
   # & 1  is the colun 

print(a3[0,1,1])   # 3 output

print(a3[1,1,0])   # 6 output

7
3
6


# Slicing

In [2]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
print(a1[2:5])
print(a1[0:8])

[2 3 4]
[0 1 2 3 4 5 6 7]


In [8]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
print(a2[0,:])
print(a2[2,:])
print(a2[:,2])

[0 1 2 3]
[ 8  9 10 11]
[ 2  6 10]


In [45]:
print(a2[1:,1:3]) 
print(a2[0::2,0::3])


[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]


In [46]:
print(a2[::2,1::2])
print(a2[1::2,0::3])


[[ 1  3]
 [ 9 11]]
[[4 7]]


In [18]:
print(a2[0:2,1:])

[[1 2 3]
 [5 6 7]]


In [22]:
import numpy as np
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [22]:
print(a3[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [23]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
# print 2nd row of 1st 2d array
a3[0,1,:]

array([3, 4, 5])

In [31]:
# miidle column of 2nd numpy array
a3[1,:,1]

array([10, 13, 16])

In [8]:
# print(3 rd 2D array) 22,23,25,26
a3 [2,1:,1:]

array([[22, 23],
       [25, 26]])

In [15]:
# print(1 & 2nd  array of 3D ) elements are 0,2,18,20
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating


In [24]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [27]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [28]:
# print every item of any dimensional array
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [30]:
# Transpose  # covert rase column
np.transpose(a2)
# or 
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [32]:
# Ravel  :- its convert abny dimensiomns array in 1D\
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

 # Stacking

In [ ]:
 # [2x2] stacking [2x2] :- horizontal   [ 2    x 4  ]
 # [2x2] stacking [2x2] :- vertical   [ 4x2 ]

# with any no of arrats

In [34]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


In [35]:
a4


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
#  horizontal stacking with a4,a5  
print(np.hstack((a4,a5)))

print("***********")
# u can repeat or add diff array too with same doimensions
print(np.hstack((a4,a5,a5,a4)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
***********
[[ 0  1  2  3 12 13 14 15 12 13 14 15  0  1  2  3]
 [ 4  5  6  7 16 17 18 19 16 17 18 19  4  5  6  7]
 [ 8  9 10 11 20 21 22 23 20 21 22 23  8  9 10 11]]


In [40]:
# vertical  stacking with a4,a5
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [41]:
# splitting  :- inverse of stacking


In [43]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# Horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [45]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
# vertical Spllitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# Numpy array vs Python list
   :-  numpy takes les time as compair to python
   :- numpy is more efficient
   :-  numpy takes less memory sspace 

In [1]:
# spped'
# list

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])

print(time.time() - start)

0.559502124786377


In [5]:
# numpy 
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
import time

start = time.time()  # current time
c = a+b
print(time.time() - start)

0.026903629302978516


In [6]:
0.55/0.02   # numpy is 27 time faster then python(approx)

27.5

In [8]:
# memory ,python list
a = [i for i in range(100000000)]
import sys
sys.getsizeof(a)  # bite size

835128600

In [13]:
# memory  , numpy array
# a = np.array(10000000,dtype = np.int32) # we can change dtype == int32,64.....
a = np.array(10000000)
sys.getsizeof(a)  # bite size

104

# Advanced indexing

In [4]:
# normal indexing and slicing
import numpy as np
a = np.arange(12).reshape(4,3)
print(a)

print("****indexing**")
print(a[1,2])

print("**slicing*****")
print(a[1:3,1:])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
****indexing**
5
**slicing*****
[[4 5]
 [7 8]]


In [16]:
# Fancy Indexing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
# i wanna 1st,3rd,4th and 6th row from a
a[[0,2,3,5]]  # index possition 

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [18]:
# Boolean indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[77, 86, 58, 84],
       [25, 73, 49, 23],
       [50, 85, 73, 34],
       [69, 27, 56, 14],
       [18, 88, 17, 23],
       [ 6,  1, 35, 45]])

In [19]:
# find the all numbeers greater than 50
a>50

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [False,  True,  True, False],
       [ True, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [20]:
# now using masking to filter the necessary(True) data
a[a>50]

array([77, 86, 58, 84, 73, 85, 73, 69, 56, 88])

In [25]:
# find out only the even numbers
print(a%2==0)

# noww filterimg it 
print("**********filter**")
a[ a% 2 == 0]

[[False  True  True  True]
 [False False False False]
 [ True False False  True]
 [False False  True  True]
 [ True  True False False]
 [ True False False False]]
**********filter**


array([86, 58, 84, 50, 34, 56, 14, 18, 88,  6])

In [30]:
# find all number greater than 50 and are even
a [(a > 50) & (a %2 == 0)]   #  " '&'  its a boolian and "
                             #   "'and' its a logical and"

# and we use boolian and in nboolian operation

array([86, 58, 84, 56, 88])

In [5]:
# find all  number which is not divisible by 7
a[ ~(a % 7 == 0 ) ]    # using not operators
# or
# a[ a % 7 != 0 ]  

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11])

# Broadcasting
   :- the term broadcasting describes how Numpy treats arrays with different shapes during arithmetic operations

   :- the smaller array is "broadcast" across the larger array so that they have compatible shapes

In [6]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [7]:
# diff shape
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]
